version: '3'

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${NAME_DB}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib.postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

